### ISSUE TITLE
media analyzer not in catalog

### ISSUE THREAD

**Issue by attinderdhillon** [endrl/jellyfin-plugin-media-analyzer#3]
### Describe the bug

After adding the repo I don't see ''media analyzer'' under Catalog.
I have tried restarting Jellyfin and even waiting for 2-3 days.

### Operating system

Ubuntu Server

### Jellyfin installation method

Official repo

### Support Bundle

Cant install

**Comment by DennisGHUA** [comment]
I have the same problem on a windows server with the latest jellyfin build 10.8.12. The instructions say "2. Install the Media Analyzer plugin from the General section" I think that should be the catalog section. But I was not able to find it.

**Comment by myzar472** [comment]
I was able to reproduce this on a fresh Jellyfin install on Ubuntu 20 LTS. As with DennisGHUA, I don't get the plugin appearing after adding the repo. 

Server Info: 
<img width="599" alt="image" src="https://github.com/endrl/jellyfin-plugin-media-analyzer/assets/9061508/66229320-424e-4572-a5a2-48ded07b6ccf">

Repos are setup correctly:
<img width="1573" alt="image" src="https://github.com/endrl/jellyfin-plugin-media-analyzer/assets/9061508/bc9b22d0-36d9-486d-a18b-f6200363e568">

The JSON loads fine in a web browser as well:
<img width="1573" alt="image" src="https://github.com/endrl/jellyfin-plugin-media-analyzer/assets/9061508/9bdbad50-f3b2-4f4f-a817-a117185a9886">

Catalog does not show anything from that repo:
<img width="1573" alt="image" src="https://github.com/endrl/jellyfin-plugin-media-analyzer/assets/9061508/087c50be-13ec-43c8-a54a-a83eaae5d976">
<img width="1573" alt="image" src="https://github.com/endrl/jellyfin-plugin-media-analyzer/assets/9061508/587e7377-b0fa-49cc-a8ad-f7e3cd892d57">
<img width="1573" alt="image" src="https://github.com/endrl/jellyfin-plugin-media-analyzer/assets/9061508/e0140f94-a1d5-49a6-8a85-a621a5e53579">

**Comment by DennisGHUA** [comment]
Upon further investigation, I noticed a discrepancy: the "targetAbi" in the JSON file is set to "10.9.0.0," while the latest stable Jellyfin version is 10.8.12.0. This means the plugin version specified in the JSON file is actually newer than the current stable release.

I found a related pull request (https://github.com/jellyfin/jellyfin/issues/4688) that addresses this by hiding plugins with a higher ABI version than what the server is currently running. This suggests that the plugin might only work with the unstable Jellyfin build, likely 10.9 and higher. Alternatively, users might have to wait until the unstable build becomes stable, and given Jellyfin's release history, this could take a while.

**Comment by Cantello** [comment]
With the unstable version (10.9), Media Analyzer can be installed but is afterwards listed as "Status: Not Supported" and it cannot be configured.

**Comment by Ryuo1** [comment]
So do we have to wait till the next Jellyfin version?

**Comment by vin86** [comment]
I modified manifest.json, changed targetABI version and it works. Link: https://raw.githubusercontent.com/vin86/medianalyzerjellyfin/main/manifest.json

**Comment by ELKER54** [comment]
Are there any updates on this? It's still not on the catalogue for me?

**Comment by sebastianpc** [comment]
Media Analyzer requires Jellyfin with Media Segments.
This is not included in Jellyfin yet, but there is an open pull request (https://github.com/jellyfin/jellyfin/pull/10530)

@endrl made a docker, with media segments included: https://github.com/endrl/segment-editor#installation

**Comment by endrl** [comment]
Release of Jellyfin is in ~6 weeks! And yes, there is no other way around. You can still use ConfusedPolarBears or another fork.

**Comment by endrl** [comment]
Bad news: We missed the deadline. Next target Jellyfin 10.10.
Good news: They want to run a faster release train now so we don't need to wait until 4.2026

**Comment by Gauvino** [comment]
> Bad news: We missed the deadline. Next target Jellyfin 10.10.
> 
> Good news: They want to run a faster release train now so we don't need to wait until 4.2026

How do you know we missed the deadline ? They haven't released it yet ?

**Comment by endrl** [comment]
Feature freeze was yesterday and the pr is tagged for 10.10 now

**Comment by Gauvino** [comment]
yes i did see this and quick question could you look at this ? https://github.com/endrl/jellyfin-plugin-media-analyzer/pull/7

**Comment by ramonskie** [comment]
it would be nice to put this information in the readme as it got me chasing dragons again :)

**Comment by endrl** [comment]
Updated the Readme, people that are looking for a ConfusedPolarBear replacement should look at [jumoog's Fork](https://github.com/jumoog/intro-skipper) as this repo is highly experimental and not ready to be used.
