### ISSUE TITLE
Stable to use on main server?

### ISSUE THREAD

**Issue by BLACK4585** [endrl/jellyfin-plugin-media-analyzer#8]
Hey, I just stumbled across your fork. You wrote that we should not mess with the main server config when using the Segments API. Is it unsafe to use? What are the possible things that could happen?
I'm interested since I want to use this plugin and aren't sure if it's already stable enough for the main server.
Also, I really need your patched Jellyfin version?

**Comment by jumoog** [comment]
> Also, I really need your patched Jellyfin version?

Yes, you do. Otherwise the plugin won't work.

**Comment by endrl** [comment]
> What are the possible things that could happen?

The database migration won't be compatible with the migration that will be merged into stable jellyfin. You need to delete the table and index when you switch back with a sqlite editor.

But you shouldn't do it, as you need also official client support. Read more here: https://github.com/endrl/jellyfin-plugin-media-analyzer/issues/4#issuecomment-1999670488
