### ISSUE TITLE
[Feature Request] Skip button on web ui as the origin repo does

### ISSUE THREAD

**Issue by xiNeRoar** [endrl/jellyfin-plugin-media-analyzer#9]
Hope there will be a clear instruction of how to get a "Skip" button on the web ui. This is one of the main features of the original repo.

**Comment by endrl** [comment]
This is not a 1:1 replacement: Please read more https://github.com/endrl/jellyfin-plugin-media-analyzer/issues/4#issuecomment-1999670488
